;; This file was generated by the `with-cache` library on 2020-12-18
(((take5 tetris synth quadU quadT)) (3) 0 () 0 () () (h - (equal) (0 . 34417) (1 . 81292) (2 . 95113) (3 . 65764) (4 . 27650) (5 . 7980) (6 . 1460) (7 . 106) (-4 . 7) (-3 . 40) (-2 . 516) (-1 . 5655)))
