;; This file was generated by the `with-cache` library on 2020-12-18
(((take5 tetris synth quadU quadT)) (3) 0 () 0 () () (h - (equal) (0 . 34851) (1 . 88514) (2 . 86860) (3 . 61654) (4 . 30304) (5 . 9554) (6 . 1991) (7 . 399) (8 . 49) (9 . 4) (-4 . 1) (-3 . 36) (-2 . 777) (-1 . 5006)))
