;; This file was generated by the `with-cache` library on 2020-12-18
(((take5 tetris synth quadU quadT)) (3) 0 () 0 () () (h - (equal) (0 . 47838) (1 . 97793) (2 . 76618) (3 . 52521) (4 . 26020) (5 . 10103) (6 . 3412) (7 . 660) (8 . 44) (9 . 3) (-3 . 98) (-2 . 644) (-1 . 4246)))
