;; This file was generated by the `with-cache` library on 2020-12-18
(((take5 tetris synth quadU quadT)) (3) 0 () 0 () () (h - (equal) (0 . 24381) (1 . 60279) (2 . 76343) (3 . 72463) (4 . 48197) (5 . 21653) (6 . 7438) (7 . 1691) (8 . 184) (9 . 2) (-3 . 171) (-2 . 912) (-1 . 6286)))
