;; This file was generated by the `with-cache` library on 2020-12-18
(((take5 tetris synth quadU quadT)) (3) 0 () 0 () () (h - (equal) (0 . 155670) (1 . 39404) (2 . 49721) (3 . 39846) (4 . 21027) (5 . 7979) (6 . 2225) (7 . 430) (8 . 63) (9 . 8) (-4 . 1) (-3 . 60) (-2 . 383) (-1 . 3183)))
