;; This file was generated by the `with-cache` library on 2020-07-12
(((sieve forth fsm fsmoo mbta morsecode zombie dungeon zordoz lnm suffixtree kcfa snake take5 acquire tetris synth gregor quadBG quadMB)) (3) 0 () 0 () () 31945)
