;; This file was generated by the `with-cache` library on 2020-11-17
(((fsm morsecode jpeg kcfa zombie zordoz)) (3) 0 () 0 () () (c (c fsm c (u . "37.50")) c (c morsecode c (u . "25.00")) c (c jpeg c (u . "37.50")) c (c kcfa c (u . "55.47")) c (c zombie c (u . "6.25")) c (c zordoz c (u . "46.88"))))
